on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64, "s390x"]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: s390x
            goos: windows
          - goarch: s390x
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
      - name: Bump version and create tag
        id: bump_tag
        run: |
          if [ -z "${{ steps.get_tag.outputs.latest_tag }}" ]; then
            new_tag="v1.0.0"
          else
            IFS='.' read -r major minor patch <<< "${{ steps.get_tag.outputs.latest_tag }}"
            patch=$((patch+1))
            new_tag="v${major}.${minor}.${patch}"
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$new_tag"
          git push origin "$new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          name: "Auto Release ${{ steps.bump_tag.outputs.new_tag }}"
          draft: false
          prerelease: false
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.23.1.linux-amd64.tar.gz"
          binary_name: "backup2gh"
          asset_name: "backup2gh-${{ matrix.goos }}-${{ matrix.goarch }}"
          md5sum: false